# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Saas


class _Communication(_Saas):
    _type = "communication"
    _icon_dir = "resources/saas/communication"


class Twillio(_Communication):
    _icon = "twillio.png"


# Aliases
